# Generated by Django 3.2.19 on 2023-06-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(max_length=4),
        ),
    ]
