# Generated by Django 3.2.19 on 2023-06-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
