# Generated by Django 2.0.2 on 2023-05-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0007_auto_20230503_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ManyToManyField(to='ejemplos.Proveedor'),
        ),
    ]
