# Generated by Django 2.0.2 on 2023-05-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0008_producto_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
