# Generated by Django 2.0.2 on 2023-05-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0011_auto_20230509_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
