# Generated by Django 2.0.2 on 2023-05-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0015_remove_producto_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Proveedor')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Proveedor')),
                ('celular', models.IntegerField()),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre empresa')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion de los productos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ManyToManyField(to='ejemplos.Proveedor'),
        ),
    ]
