# Generated by Django 2.0.2 on 2023-05-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0016_auto_20230509_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
