# Generated by Django 2.0.2 on 2023-05-10 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0018_producto_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos', models.ManyToManyField(through='ejemplos.DetalleOrdenCompra', to='ejemplos.Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplos.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplos.OrdenCompra'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplos.Producto'),
        ),
    ]
