# Generated by Django 2.0.2 on 2023-05-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0019_auto_20230510_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total',
            field=models.IntegerField(),
        ),
    ]
