# Generated by Django 2.0.2 on 2023-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0020_auto_20230510_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
