# Generated by Django 2.0.2 on 2023-05-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0023_auto_20230510_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleordencompra',
            old_name='precio',
            new_name='precio_unitario',
        ),
        migrations.RenameField(
            model_name='ordencompra',
            old_name='fecha_entrega',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='fecha_orden',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='total',
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
