# Generated by Django 2.0.2 on 2023-05-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0024_auto_20230510_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='fecha',
            new_name='fecha1',
        ),
    ]
