# Generated by Django 2.0.2 on 2023-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0025_auto_20230510_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='fecha1',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='total',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='productos',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
