# Generated by Django 2.0.2 on 2023-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0026_auto_20230510_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
