# Generated by Django 2.0.2 on 2023-05-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0027_auto_20230510_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='total',
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
