# Generated by Django 2.0.2 on 2023-05-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0030_auto_20230510_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='precio_unitario',
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplos.OrdenCompra'),
        ),
    ]
