# Generated by Django 2.0.2 on 2023-05-23 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0032_auto_20230523_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ejemplos.OrdenCompra'),
        ),
    ]
