# Generated by Django 2.0.2 on 2023-05-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0033_auto_20230523_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.CharField(max_length=100),
        ),
    ]
