# Generated by Django 2.0.2 on 2023-05-24 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0034_auto_20230523_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='precio',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplos.Proveedor'),
        ),
    ]
