# Generated by Django 2.0.2 on 2023-05-24 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0035_auto_20230524_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='orden_compra',
        ),
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='producto',
        ),
        migrations.RenameField(
            model_name='ordencompra',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='DetalleOrdenCompra',
        ),
        migrations.AddField(
            model_name='itemorden',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ejemplos.OrdenCompra'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplos.Producto'),
        ),
    ]
