# Generated by Django 2.0.2 on 2023-05-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0037_auto_20230524_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorden',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
