# Generated by Django 2.0.2 on 2023-05-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0038_auto_20230524_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorden',
            name='orden_compra',
        ),
        migrations.RemoveField(
            model_name='itemorden',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='ItemOrden',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
    ]
