# Generated by Django 2.0.2 on 2023-05-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordencompra', '0003_auto_20230524_0219'),
        ('ejemplos', '0040_auto_20230524_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
