# Generated by Django 3.2.19 on 2023-06-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0042_categoria_detalleordencompra_ordencompra_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='DetalleOrdenCompra',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
