# Generated by Django 2.0.2 on 2023-05-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre 1 del cliente')),
                ('nombre2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre 2 del cliente')),
                ('nombre3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre 3 del cliente')),
                ('apellido1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido 2 del cliente')),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('direccion_postal', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre1'],
            },
        ),
    ]
