# Generated by Django 2.0.2 on 2023-05-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido 2 del cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido 1 del cliente'),
        ),
    ]
