# Generated by Django 3.2.19 on 2023-06-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncliente', '0002_auto_20230508_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(null=True),
        ),
    ]
