# Generated by Django 3.2.19 on 2023-06-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncliente', '0003_alter_cliente_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
