# Generated by Django 3.2.19 on 2023-06-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncliente', '0004_auto_20230604_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion_postal',
            field=models.IntegerField(null=True),
        ),
    ]
