# Generated by Django 2.0.2 on 2023-05-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordencompra', '0002_auto_20230524_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Producto'),
        ),
    ]
