# Generated by Django 3.2.19 on 2023-06-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_correo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correo',
        ),
    ]
