# Generated by Django 3.2.19 on 2023-06-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0004_delete_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='archivo',
            field=models.FileField(null=True, upload_to='cotizaciones/'),
        ),
    ]
